# -*- coding: utf-8 -*-
"""AUD Assignment 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17-ri4ZInAWXjgGVc1KIIsUC9Ami3oOsq

# Building a Crowdsourced Beer Recommender System  

- MEMBERS: Abhiroop Kumar, Alina Hota, Manoranjith Anandan, Simoni K Dalal, Rohan K David, Keerti Rawat
- GROUP NO.: Group 8  
- COURSE: Analytics for Unstructured Data  
- ASSINGMENT NO.: Assingment 2  
- DUE DATE: 26th September by 11:59 p.m.

## Executive Summary

We developed a beer recommender system that leverages customer reviews to connect user-specified attributes (e.g., *black, thick, bourbon*) with beers that drinkers actually describe in those terms. By moving from simple bag-of-words and sentiment models to domain-trained embeddings, the system learns beer-specific language and produces recommendations that align closely with real consumer perceptions. The approach ensures interpretability, avoids popularity bias, and demonstrates how natural language can drive personalized, transparent recommendations.

---

## Business Applications

* **Personalized Recommendations**: Enable new customers to find beers instantly by selecting taste attributes instead of browsing ratings.

* **Product Positioning**: Breweries can highlight the attributes most valued by consumers and use them in marketing or packaging.
* **Customer Engagement**: Platforms can provide interactive “attribute search” tools, making discovery more intuitive than rating-based filters.
* **Cross-Sell & Bundling**: Curate assortments around shared attributes (e.g., “Bourbon Barrel Stout Collection”) to increase basket size.
* **On-Premise Menus**: Taprooms can offer kiosks or QR menus where guests enter desired attributes and instantly see the best pours.

### NOTE

> PLEASE DO NOT RUN THE WHOLE FILE!!  
- _Recommended_  
Please upload the IPYNB and the CSV (dataset) files to Google Colab before running the notebook (due to `gensim` package installation issues in  local system)  
- Task A contains the Web Scraper code which takes an average of 3 hrs to run  
- Instead, run the below 2 import cells and then shift to code cell where the scraped dataset is imported in the notebook  
- To search the cell, please do _Ctrl+F_ and type in the search box, `NOTE TO PROFESSOR/TA`

#### Loading Packages
"""

# Install stable versions known to work well with gensim
!pip install numpy==1.26.4 scipy==1.13.1

# Install necessary libraries (only if not already installed)
!pip install selenium webdriver-manager pandas bs4 lxml gensim spacy

# ===============================
# Imports
# ===============================
import time
import re
import string
from urllib.parse import urljoin

import numpy as np
import pandas as pd

# Selenium
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager

# NLP / Sentiment
import nltk
from nltk.sentiment import SentimentIntensityAnalyzer
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

# ML / Similarity
from sklearn.metrics.pairwise import cosine_similarity
from gensim.models import Word2Vec

# SpaCy
import spacy

# ===============================
# NLTK Resources Setup
# ===============================
nltk.download("punkt")
nltk.download("punkt_tab")   # extra resource sometimes missing
nltk.download("vader_lexicon")
nltk.download("stopwords")
nltk.download("wordnet")

# ===============================
# SpaCy Model Load
# ===============================
!python -m spacy download en_core_web_md
nlp = spacy.load("en_core_web_md")

# ===============================
# Initialize Sentiment Analyzer
# ===============================
sia = SentimentIntensityAnalyzer()

# ===============================
# Stopwords
# ===============================
stop_words = set(stopwords.words("english"))

# ===============================
# TF-IDF
# ===============================
from sklearn.feature_extraction.text import TfidfVectorizer
from collections import Counter

"""- As discussed above, after running the 2 import cells, go to the cell where the scraped dataset is imported into the notebook.  
- To search the cell, please do _Ctrl+F_ and type in the search box, `NOTE TO PROFESSOR/TA`

## Task A: Extracting the voices of Beer Lovers

**Approach**

BeerAdvocate website has the Top-250 beers selected based on user ratings along with their metadata. We scraped both the beers and their metadata, as well as the links to their review pages. To scrape the reviews, we followed the approach below:
- Manual login once (pagination requires it).
- Enter each beer’s review page through its scraped link.
- Trial Run: For one beer, recover the first 100 reviews that have at least 50 characters.
    - The 50-character criterion ensures we only include meaningful reviews.
- Full Run: For all 250 beers, scrape the first 100 reviews that meet the 50-character requirement.
    - If a beer had fewer than 100 reviews, we collected all available valid reviews.

---


**Why we capped at 100 reviews per beer**

The original guideline was to limit the overall dataset size to ~10k reviews. If we had followed this literally, the dataset would have been dominated by a small number of highly popular beers that have thousands of reviews each. In that scenario, the “head” of the distribution would fill the dataset, and many beers in the long tail would not appear at all.

To avoid this imbalance, we capped each beer at 100 reviews maximum (≥50 characters). This choice ensures that:
- Every beer gets representation, whether it has 10 reviews or 10,000 reviews on BeerAdvocate.
- The dataset is balanced and diverse, rather than skewed toward a handful of popular beers.
- We still end up with a manageable dataset (~19.5k reviews) that is computationally feasible but more inclusive.

---

**Why this makes sense for recommendations**

While our cap pushes the dataset well above the suggested 10k reviews, it better serves the end goal of long-tail recommendations:

- It prevents the system from only learning from overwhelmingly popular beers.
- It gives less famous but highly rated beers a fair chance to surface in recommendations if they align with a user’s specified attributes and sentiments.
- It balances practicality (dataset size) with fairness (equal opportunity across all 250 beers).
"""

# -------- CONFIG --------

TOP_URL = "https://www.beeradvocate.com/beer/top-rated/"

HEADLESS = False

PAUSE = 0.25             # small pause between page actions

LIMIT_PER_BEER = 100     # cap reviews per beer

MIN_REVIEW_LEN = 50      # keep only review_text >= 50 chars

# ------------------------

# XPaths you provided for the review block area
XPATH_REVIEW_BLOCKS = "//*[@id='rating_fullview_content_2']"        # repeated id across reviews
REL_REVIEW_TEXT     = ".//div"                                      # long text inside the block
REL_SUBSCORES_SAFE  = ".//span[contains(@class,'muted') and contains(.,'look:')]"  # 'look: x | smell: y | ...'
REL_OVERALL_BY_CLASS = ".//span[contains(@class,'BAscore_norm')]"                   # normalized reviewer overall


# precompiled regex
RE_OVERALL_NEAR_5 = re.compile(r"\b([0-9]+(?:\.[0-9]+)?)\b(?=.*?/5)")
RE_SUB = lambda lbl: re.compile(rf"{lbl}\s*:\s*([0-9.]+)", re.I)
RE_JUNK_LINE = re.compile(r"^(Rated:|Reviewed by:)\b", re.I)
RE_DATE = re.compile(r"(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s+\d{1,2},\s+\d{4}", re.I)
RE_META_LINE   = re.compile(r"^(Rated:|Reviewed by:)\b", re.I)
RE_SUBSCORE_LN = re.compile(r"\b(look|smell|taste|feel|overall)\s*:\s*[0-9.]+", re.I)

MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
          "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]

"""#### Defining Functions"""

# ======== bootstrap & login ========

def start_driver():
    opts = Options()
    if HEADLESS:
        opts.add_argument("--headless=new")
    opts.add_argument("--window-size=1280,1000")
    opts.page_load_strategy = "eager"  # don't wait for ads/analytics

    # Block heavy assets
    prefs = {
        "profile.managed_default_content_settings.images": 2,
        "profile.managed_default_content_settings.stylesheets": 2,
        "profile.managed_default_content_settings.fonts": 2,
        "profile.managed_default_content_settings.plugins": 2,
    }
    opts.add_experimental_option("prefs", prefs)

    d = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=opts)
    d.implicitly_wait(2)   # keep small
    return d

def manual_login_once(driver):
    driver.get("https://www.beeradvocate.com/")
    print(">>> Log in manually in the opened browser window.")
    input(">>> Press Enter here AFTER you finish logging in... ")

# ======== Top-250 meta ========

def scrape_top250_meta(driver):
    driver.get(TOP_URL)
    WebDriverWait(driver, 15).until(
        EC.presence_of_element_located((By.XPATH, "//table//tr//a[starts-with(@href,'/beer/profile/')]"))
    )

    rows = driver.find_elements(By.XPATH, "//table//tr[td/a[starts-with(@href,'/beer/profile/')]]")
    out = []
    for r in rows:
        a = r.find_element(By.XPATH, ".//td/a[starts-with(@href,'/beer/profile/')]")
        beer_link = a.get_attribute("href")
        try:
            beer_name = a.find_element(By.TAG_NAME, "b").text.strip()
        except:
            beer_name = a.text.strip()

        span = r.find_element(By.XPATH, ".//td/span[@class='muted']")
        brewer_a = span.find_elements(By.XPATH, ".//a[starts-with(@href,'/beer/profile/')]")
        brewer_name = brewer_a[0].text.strip() if brewer_a else None
        style_a = span.find_elements(By.XPATH, ".//a[starts-with(@href,'/beer/top-styles/')]")
        beer_style = style_a[0].text.strip() if style_a else None
        m = re.search(r"([0-9.]+%)", span.text)
        abv = m.group(1) if m else None

        out.append({
            "beer_name": beer_name,
            "brewer_name": brewer_name,
            "beer_style": beer_style,
            "abv": abv,
            "beer_link": beer_link
        })

    return pd.DataFrame(out, columns=["beer_name","brewer_name","beer_style","abv","beer_link"])

# ======== One-beer reviews ========

def parse_subscores(text):
    # e.g. "look: 4.5 | smell: 4.75 | taste: 4.25 | feel: 4 | overall: 5"
    def grab(lbl):
        m = re.search(rf"{lbl}\s*:\s*([0-9.]+)", text, flags=re.I)
        return float(m.group(1)) if m else None
    return grab("look"), grab("smell"), grab("taste"), grab("feel"), grab("overall")


def clean_review_text_fast(t: str) -> str:
    if not t:
        return ""
    # normalize whitespace quickly (faster than regex)
    t = " ".join(t.split())

    # quick skips
    low = t.lower()
    if low.startswith("rated:") or low.startswith("reviewed by:"):
        return ""

    # remove inline sections we never want
    cut_idx = len(t)
    for kw in ("Image:", "View:"):
        k = t.find(kw)
        if k != -1:
            cut_idx = min(cut_idx, k)
    t = t[:cut_idx].rstrip()

    # drop trailing "Report"
    if t.endswith(" Report"):
        t = t[:-7].rstrip()

    # drop trailing date like "Mar 25, 2025"
    # quick scan from the end; no regex needed
    parts = t.rsplit(" ", 3)  # try to catch "... Mon DD, YYYY"
    if len(parts) == 4 and parts[-3][:3] in MONTHS and parts[-2].rstrip(",").isdigit() and parts[-1].isdigit():
        # confirm it looks like "Mon DD, YYYY"
        t = " ".join(parts[:-3]).rstrip()

    return t



CSS_REVIEW_BLOCKS = "#rating_fullview_content_2"

def clean_review_text_fast(s: str) -> str:
    if not s: return ""
    s = " ".join(s.split())
    if s.endswith(" Report"):
        s = s[:-7].rstrip()
    s = RE_DATE.sub("", s)
    s = s.replace("Image:", "").replace("View:", "")
    return s.strip(" .:-\n\t")

def extract_reviews_from_page(driver, beer_base_link):
    WebDriverWait(driver, 4, poll_frequency=0.15).until(
        EC.presence_of_all_elements_located((By.CSS_SELECTOR, CSS_REVIEW_BLOCKS))
    )
    blocks = driver.find_elements(By.CSS_SELECTOR, CSS_REVIEW_BLOCKS)

    rows = []
    for b in blocks:
        text = (b.get_attribute("innerText") or "").strip()
        if not text:
            continue

        # reviewer_overall (normalized)
        m_overall = RE_OVERALL_NEAR_5.search(text)
        reviewer_overall = float(m_overall.group(1)) if m_overall else None

        # subscores
        def grab(lbl):
            m = RE_SUB(lbl).search(text);  return float(m.group(1)) if m else None
        look  = grab("look");  smell = grab("smell");  taste = grab("taste")
        feel  = grab("feel");  overall_component = grab("overall")


        # --- derive review text from the block (strict filtering) ---
        lines = [ln.strip() for ln in text.splitlines() if ln.strip()]

        # drop meta & subscore lines entirely
        content_lines = [ln for ln in lines if not RE_META_LINE.match(ln) and not RE_SUBSCORE_LN.search(ln)]
        if not content_lines:
            continue

        # take the longest remaining content (or join; longest is usually fine)
        candidate = max(content_lines, key=len)
        # candidate = " ".join(content_lines)  # <- use this instead if you prefer to merge lines
        review_text = clean_review_text_fast(candidate)

        # final guard
        if RE_META_LINE.match(review_text) or RE_SUBSCORE_LN.search(review_text):
            continue



        #Append all the rows
        if review_text and len(review_text) >= MIN_REVIEW_LEN:
            rows.append({
                "beer_link": beer_base_link,
                "reviewer_overall": reviewer_overall,
                "look": look, "smell": smell, "taste": taste, "feel": feel,
                "overall_component": overall_component,
                "review_text": review_text
            })

    return rows



def find_next_url(driver):
    """
    Generic Next finder:
    - Find the pagination bar under #ba-content
    - Return the href of the anchor whose visible text contains 'next' (case-insensitive)
    - If 'next' is muted (final page), it's a <span>, so we return None
    """
    # Grab all anchors inside the pagination span; ignore indexes entirely
    anchors = driver.find_elements(By.XPATH, "//*[@id='ba-content']//span//a")
    for a in anchors:
        label = a.text.strip().lower()
        if "next" in label:
            href = a.get_attribute("href")
            if href:
                return urljoin(driver.current_url, href)
    return None  # no next (either last page or pagination missing)


def scrape_one_beer_reviews(driver, beer_base_link):
    driver.get(beer_base_link)

    collected = []
    visited = set()

    while True:
        cur = driver.current_url
        if cur in visited:
            break  # safety: avoid loops if site glitches back to same page
        visited.add(cur)

        rows = extract_reviews_from_page(driver, beer_base_link)
        need = LIMIT_PER_BEER - len(collected)
        if need > 0:
            collected.extend(rows[:need])

        if len(collected) >= LIMIT_PER_BEER:
            break

        next_url = find_next_url(driver)
        if not next_url:
            break
        driver.get(next_url)

    return pd.DataFrame(collected, columns=["beer_link","reviewer_overall","look","smell","taste","feel","overall_component","review_text"])

# ======== run Top-250 meta scrape ========
d = start_driver()
manual_login_once(d)  # login once so the session is valid going forward (safe to keep)

df_top = scrape_top250_meta(d)
df_top.to_csv("top250_meta.csv", index=False)
print("Saved top250_meta.csv:", len(df_top), "rows")

d.quit()

# ======== run one beer review example ========

# choose which beer to test (0-based index into top250 dataframe)
BEER_IDX = 0  # change this to test other beers

beer_link = df_top.loc[BEER_IDX, "beer_link"]
print(f"Testing beer #{BEER_IDX+1}: {beer_link}")

d = start_driver()
manual_login_once(d)  # required for pagination
df_reviews = scrape_one_beer_reviews(d, beer_link)
df_reviews.to_csv("one_beer_reviews.csv", index=False)
print("Saved one_beer_reviews.csv:", len(df_reviews), "rows")

d.quit()

# ======== run ALL beers review scrape (append mode) ========

OUT = "all_beer_reviews.csv"

# write header once
pd.DataFrame(columns=["beer_link","reviewer_overall","look","smell","taste","feel","overall_component","review_text"]).to_csv(OUT, index=False)

d = start_driver()
manual_login_once(d)

for beer_link in df_top["beer_link"]:
    df_reviews = scrape_one_beer_reviews(d, beer_link)
    if not df_reviews.empty:
        df_reviews.to_csv(OUT, mode="a", header=False, index=False)

d.quit()
print("Saved to", OUT)

#Creating a combined dataset of the Beer's metadata and reviews (upto 100 reviews)

# Load your saved CSVs
df_reviews = pd.read_csv("all_beer_reviews.csv")
df_top = pd.read_csv("top250_meta.csv")

# Merge on beer_link
df = pd.merge(df_top, df_reviews, on="beer_link")

#Keeping only the necessary columns
df = df[["beer_name","review_text","reviewer_overall"]]


print("Final Dataset:", df.shape)
display(df.head())

"""NOTE:
Column Names and their Meanings are given below
- `product_name : beer_name`

- `product_review : review_text`

- `user_rating : reviewer_overall`

**Remove outlier fields that have only texts like "Rated by person-1"**
"""

# regex to catch "Rated: X by Y from Z" type reviews
RE_META = re.compile(r"^Rated:\s*\d+(\.\d+)?\s+by\s+", re.I)

# filter df: keep only rows where review_text is NOT matching the pattern
df = df[~df["review_text"].str.match(RE_META, na=False)]

print("Shape of the final Dataframe:",df.shape)

display(df.head())

#Storing the Beer Reviews into a CSV

df.to_csv("beer_review_dataset.csv", index=False)
print("Saved beer_review_dataset.csv:", len(df), "rows")

"""### NOTE FOR PROFESSOR / TA

After you have run the 2 import cells at the top of the notebook, please run the python notebook from the below cell onwards.

> _Pre-requisite:_ The 2 import statements at the top of the notebook should already have been run and both the files should already be uploaded to Google Colab before running the file.  
"""

df = pd.read_csv("beer_review_dataset.csv")

print(df.shape)

"""## Task B: Finding the Perfect match - Recommending Beers Based on Attributes


**Approach:** Beer Recommendation using User Preferences with **Bag-of-Words Frequency Analysis + Sentiment Scoring**, ranked by **Cosine Similarity** to the user profile

"""

#preview of the dataset
df.head()

"""**Obtaining word frequencies from the scraped reviews**"""

def preprocess(text):
    tokens = word_tokenize(text.lower())  # lowercase + tokenize
    tokens = [t for t in tokens if t.isalpha()]  # keep only words
    tokens = [t for t in tokens if t not in stop_words]  # remove stopwords
    return set(tokens)  # use set so each word is counted only once per review

#applying the pre-processing function
df["tokens"] = df["review_text"].apply(preprocess)


#counting the words appearing in reviews
from collections import Counter

word_counts = Counter()

for token_set in df["tokens"]:
    word_counts.update(token_set)  # adds 1 per review per word

#converting the result into a dataframe
word_freq_df = pd.DataFrame(word_counts.items(), columns=["word", "freq_count"])
word_freq_df = word_freq_df.sort_values(by="freq_count", ascending=False).reset_index(drop=True)

#top 50 words
print(word_freq_df.head(50))

"""The top 50 words are identified from the scraped reviews. The frequency scoring for the words are such that if a word appaears multiple times in a review, it is only counted as one. In short, for each word the counts depict in how many reviews that wword appears.

The attributes for the beer based on which beers are to be recommended are chosen from the top 50 words that appear in the scraped reviews.

**Attributes Identification and Categorization**




The Attributes that a beer can have can be broadly divided into 3 categories: The attributes are identified from the top 50 words and categorized into these 3 categories.

**Appearance** : Based on color of the beer (dark, light, black, white, orange)

**Flavor** : Based on the taste of the beer (bitterness, sweet, malt, coffee, vanilla, chocolate, citrus, bourbon, fruit)

**Mouthfeel/Texture**: Based on the texture of the beer or the feel while drinking the beer (smooth, thick ,lacing, carbonation)

Next, a lift analysis is done among these 18 potential attributes and 3 attributes are selected from these 18 which are then considered to be the user's specification of attributes for a beer.

**Lift calculation for the attributes of interest**
"""

N = len(df)  # total reviews

# attributes of interest
attributes = ["sweet", "smooth", "dark","light","white","black","carbonation","malt","lacing","thick","orange","coffee","vanilla",
              "chocolate","citrus","bourbon","fruit","bitterness"]

# frequency per attribute (#reviews containing the word)
attr_counts = {
    w: sum(1 for tokens in df["tokens"] if w in tokens)
    for w in attributes
}

from itertools import combinations

# co-occurrence counts between attributes
co_counts = {
    (w1, w2): sum(1 for tokens in df["tokens"] if w1 in tokens and w2 in tokens)
    for w1, w2 in combinations(attributes, 2)
}

#lift calculation
lift_results = []

for (w1, w2), co in co_counts.items():
    p_w1 = attr_counts[w1] / N
    p_w2 = attr_counts[w2] / N
    p_w1w2 = co / N

    if p_w1 > 0 and p_w2 > 0:  # avoid division by zero
        lift = p_w1w2 / (p_w1 * p_w2)
    else:
        lift = None

    lift_results.append({
        "word1": w1,
        "word2": w2,
        "count_w1": attr_counts[w1],
        "count_w2": attr_counts[w2],
        "co_count": co,
        "lift": lift
    })

lift_df = pd.DataFrame(lift_results)
lift_df=lift_df.sort_values(by='lift',ascending=False)
lift_df.head(160)

"""####
The lift analysis is helpful as it helps to identify which attributes are not to be chosen together while a user is mentioning his/her preferences:

(In general, more the co-mentions or lift value, greater is the chance that these attributes are closely related to each other)

For example,(white, orange) - lift of 3.41 but it doesn't make sense to give 2 attributes that fall under the appearance category.

Another such case is the combination of (coffee,chocolate) - lift of 3.16.

(coffee, citrus) - lift of 0.22, Also chances are very less that a beer can have both have a coffee and a citrus flavor.

(white,black) - lift of 0.195 . Also makes sense, as a beer can't be white and black at the same time.

From the lift analysis, the attributes are chosen for recommendation in such a manner that the l**ift values among the pairs are high** and also the attributes fall into the **3 defined categories**.

The 3 attributes chosen for the recommendation are **black**, **thick** and **bourbon**. These attributes fall into the **appearance**, **texture** and **flavor** categories respectively and the lift values for the pairs are:

**(black,thick) =3.01, (thick,bourbon) =1.75, (black,bourbon)=2.77**

#### **Building the Recommender System based on BoW, Sentiment Analysis and Cosine Similarity**

The Recommendation System is built in a 3 stage process:

1. **Bag of Words(BoW)** - The user query/ preference vector is based on the attributes specified ['white','lacing','citrus']. So for each review for each beer, the BoW representation of these attributes is just a presence or absence vector (0/1) i.e it will be of the form [1/0,1/0,1/0]. This approach ensures that reviews with less mentions of these attributes and reviews that overly mention these attributes have a same weightage in terms of the BoW representation.

2. **Sentiment Analysis** - For each review for each beer, if each of these 3 attributes are mentioned multiple times say white (5 times), lacing (3 times) and citrus (2 times), the sum value of the weighted sentiment associated with that attribute is calculated to a get a sentiment score for each of the attributes. A sentiment score vector is then obtained for each review for each beer say [0.4,0.7, 0.1]. The sentiment analyzer used here is VADER. The sentiment scoring approach is a weighted scoring approach such that as the distance of the word describing the attribute mention increases, that attribute mention gets a lower sentiment score.



*   Once, the BoW and Sentiment Analysis is done for each review and for each beer, the product of the BoW and Sentiment Scores are taken to get a combined vector.

*   This combined vector is then aggregated across multiple reviews of a beer by taking the average of the combined vectors. (As averaging ensures that beers with less reviews and beers with more reviews are treated similarly as opposed to summing the combined vectors across the reviews). However, while averaging, only the reviews where any of these 3 attributes that are mentioned are considered. (Say if there are 100 reviews for a beer, only 20 reviews would have these attribute mentions. So while averaging, 20 reviews are considered instead of the whole 100 reviews for that beer.)


3. **Cosine Similarity** - Finally, the cosine similarity is computed for each of the beer vectors and the user query/user preference vector (which is of the form [1,1,1]) and the beers that have the highest cosine similarity are recommended to the user.
"""

# Initialize
sia = SentimentIntensityAnalyzer()
stop_words = set(stopwords.words("english"))
lemmatizer = WordNetLemmatizer()

# 1. Attributes
attributes = ["black", "thick", "bourbon"]

# 2. Robust preprocessing function
def preprocess_tokens(text):
    tokens = re.findall(r'\b[a-zA-Z]+\b', text.lower())
    clean_tokens = []
    for t in tokens:
        t = re.sub(r'(.)\1{2,}', r'\1', t)   # normalize repeated letters
        t = lemmatizer.lemmatize(t)          # lemmatize
        if t not in stop_words:
            clean_tokens.append(t)
    return clean_tokens

# 3. Distance-weighted sentiment scoring for each attribute
def get_weighted_attr_scores(text):
    tokens = preprocess_tokens(text)
    attr_scores = {}
    attr_mentioned = False

    for attr in attributes:
        mention_scores = []
        for i, token in enumerate(tokens):
            if token == attr:
                attr_mentioned = True
                # Define a larger context window
                window_tokens = tokens[max(0, i-6): i+7]
                # Compute distance-weighted sentiment
                weighted_sum, weight_total = 0.0, 0.0
                for j, w in enumerate(window_tokens):
                    dist = abs((max(0, i-6) + j) - i)
                    if dist == 0:
                        continue  # skip the attribute word itself
                    score = sia.polarity_scores(w)["compound"]
                    weight = 1 / (dist + 1)  # closer words get more weight
                    weighted_sum += weight * score
                    weight_total += weight
                if weight_total > 0:
                    mention_scores.append(weighted_sum / weight_total)

        # sum across mentions of this attribute in the review
        attr_scores[attr] = sum(mention_scores) if mention_scores else 0.0

    return attr_scores if attr_mentioned else None

# 4. Apply to reviews
df["weighted_attr_scores"] = df["review_text"].fillna("").apply(get_weighted_attr_scores)

# Drop reviews with no relevant attributes
df = df.dropna(subset=["weighted_attr_scores"])

# 5. Aggregate to beer level (average across reviews where attributes appear)
beer_profiles = {beer: {attr: [] for attr in attributes} for beer in df["beer_name"].unique()}

for _, row in df.iterrows():
    beer = row["beer_name"]
    for attr in attributes:
        beer_profiles[beer][attr].append(row["weighted_attr_scores"][attr])

# Average per beer per attribute
beer_matrix = []
beer_names = []

for beer, attr_dict in beer_profiles.items():
    beer_names.append(beer)
    beer_vector = []
    for attr in attributes:
        if len(attr_dict[attr]) > 0:
            beer_vector.append(np.mean(attr_dict[attr]))
        else:
            beer_vector.append(0.0)
    beer_matrix.append(beer_vector)

beer_df = pd.DataFrame(beer_matrix, columns=attributes, index=beer_names)

# 6. Recommender function (query vector unnormalized)
def recommend_beers(query_attrs, top_k=3):
    query_vector = np.array([1.0 if attr in query_attrs else 0.0 for attr in attributes]).reshape(1, -1)
    sims = cosine_similarity(query_vector, beer_df.values)[0]

    beer_df_copy = beer_df.copy()
    beer_df_copy["similarity"] = sims
    return beer_df_copy.sort_values(by="similarity", ascending=False).head(top_k)

# 7. Run recommender
user_query = ["black", "thick", "bourbon"]
results = recommend_beers(user_query, top_k=3)

print("\nTop 3 recommended beers:")
print(results[["similarity"]])

"""**Based on the attributes specified by the user:**
1. black
2. thick
3. bourbon


**The top 3 recommended beers and their Cosine Similarity are:**

*   **The Abyss: 0.994**
*   **Barrel-Aged Sump Coffee Stout: 0.992**
*   **O.W.K.: 0.984**




"""

# Compute similarity scores for all beers once
query_vector = np.array([1.0 if attr in user_query else 0.0 for attr in attributes]).reshape(1, -1)
sims_all = cosine_similarity(query_vector, beer_df.values)[0]

# Add similarity as a column to beer_df
beer_df_with_sim = beer_df.copy()
beer_df_with_sim["similarity"] = sims_all

# Top 3 beers
top3_beers = beer_df_with_sim.sort_values(by="similarity", ascending=False).head(3)
print("\nTop 3 beers with sentiment and similarity:")
print(top3_beers)

# Bottom 3 beers
bottom3_beers = beer_df_with_sim.sort_values(by="similarity", ascending=True).head(3)
print("\nBottom 3 beers with sentiment and similarity:")
print(bottom3_beers)

"""The cosine similarity values are close to 0.99 for the top 3 beers that were recommended since the sentiment scores across the the 3 attributes for each of the these beers are very close to each other. Hence obtaining a similarity score close to 1 when compared with the user query vector of [1,1,1].

Also for the bottom 3 beers, the sentiment scores of the 3 attributes for each of the beers are either negative or zero to obtain a low cosine similarity score with the user query vector of [1,1,1].

**Top 20 recommended beers based on the user preference of ['black', 'thick', 'bourbon']**
"""

#getting the top 20 beer recommmendations based on ['black','thick','bourbon']
results = recommend_beers(user_query,top_k=20)
print('\nTop 20 recommended beers:')
print(results[['similarity']])

"""From the top 20 recommendations, it can be observed that the range in cosine similarity scores is from 0.99 to 0.90.

BoW approach looks for the exact match of the attributes in the reviews. For a more nuanced and accurate recommendation, word vectors/custom embeddings could do a better job.

# TASK C: Word Vectors vs Bag-of-Words - Smarter Beer Matching?
"""

# Load models
nlp = spacy.load("en_core_web_md")
sia = SentimentIntensityAnalyzer()

"""1. Prepare dataframe (for Task C)"""

# Create clone dataframe
df_taskc = df.copy()

# Ensure expected columns exist
df_taskc = df_taskc.dropna(subset=["beer_name", "review_text"])
df_taskc = df_taskc.reset_index(drop=True)

print(f"Shape of cloned dataframe: {df_taskc.shape}")

# Preview dataframe
df_taskc.head()

"""2. Attributes (From `TASK B`)"""

attributes = ["black", "bourbon", "thick"]
print(f"User-specific attributes: {attributes}")

"""3. Extract attribute sentiment per review"""

def get_attr_sentiment_scores_taskc(text):
    tokens = re.findall(r"\b[a-zA-Z]+\b", text.lower())
    attr_scores = {}
    attr_mentioned = False

    for attr in attributes:
        scores = []
        for i, token in enumerate(tokens):
            if token == attr:
                attr_mentioned = True
                context = " ".join(tokens[max(0, i-3): i+4])  # local context
                scores.append(sia.polarity_scores(context)["compound"])
        # Use SUM instead of average
        attr_scores[attr] = sum(scores) if scores else 0.0

    return attr_scores if attr_mentioned else None

df_taskc["attr_sentiment_scores"] = df_taskc["review_text"].fillna("").apply(get_attr_sentiment_scores_taskc)

# Keep only reviews mentioning at least one attribute
df_taskc = df_taskc.dropna(subset=["attr_sentiment_scores"]).reset_index(drop=True)

# View attribute scores
attr_df = df_taskc["attr_sentiment_scores"].apply(pd.Series)
attr_result = pd.concat([df_taskc["beer_name"], attr_df], axis=1)
print(attr_result.head(10))

"""4. Build beer profiles (weighted review vectors)"""

beer_profiles_taskc = {}

for _, row in df_taskc.iterrows():
    beer = row["beer_name"]
    review = row["review_text"]
    attr_scores = row["attr_sentiment_scores"]

    # Get spaCy review vector (avg over tokens)
    doc = nlp(review.lower())
    tokens = [t.vector for t in doc if not t.is_stop and not t.is_punct and t.has_vector]
    if not tokens:
        continue
    review_vec = np.mean(tokens, axis=0)

    # Total sentiment score = sum of attribute scores for this review
    total_score = sum(attr_scores.values())

    if total_score == 0:
        continue  # skip neutral reviews

    weighted_vec = review_vec * total_score

    if beer not in beer_profiles_taskc:
        beer_profiles_taskc[beer] = {"vectors": [], "scores": []}

    beer_profiles_taskc[beer]["vectors"].append(weighted_vec)
    beer_profiles_taskc[beer]["scores"].append(total_score)

"""5. Aggregate beer vectors"""

beer_matrix_taskc = []
beer_names_taskc = []

for beer, data in beer_profiles_taskc.items():
    total_weight = sum(data["scores"])
    if total_weight == 0:
        continue
    avg_vec = np.mean(data["vectors"], axis=0)  # already scaled by sentiment
    beer_matrix_taskc.append(avg_vec)
    beer_names_taskc.append(beer)

beer_df_taskc = pd.DataFrame(beer_matrix_taskc, index=beer_names_taskc)

print(f"Shape of beer dataframe: {beer_df_taskc.shape}")

"""6. Recommender"""

# Create recommender function
def recommend_beers_taskc(query_attrs, top_k=3, bottom_k=None):
    query_tokens = [nlp(word).vector for word in query_attrs if nlp(word).has_vector]
    if not query_tokens:
        return None
    query_vec = np.mean(query_tokens, axis=0).reshape(1, -1)

    sims = cosine_similarity(query_vec, beer_df_taskc.values)[0]

    beer_df_copy = beer_df_taskc.copy().reset_index().rename(columns={"index": "beer_name"})
    beer_df_copy["similarity"] = sims

    # Deterministic sorting
    beer_df_copy = beer_df_copy.sort_values(by=["similarity", "beer_name"], ascending=[False, True])

    if bottom_k is not None:
        return beer_df_copy.sort_values(by="similarity", ascending=True).head(bottom_k)
    return beer_df_copy.head(top_k)

# Run recommender (Top 5)
top5 = recommend_beers_taskc(["black", "bourbon", "thick"], top_k=5)
print(f"Top 5 recommended beers:\n {top5[["beer_name", "similarity"]]}")

# Run recommender (Bottom 5)
bottom5 = recommend_beers_taskc(["black", "bourbon", "thick"], bottom_k=5)
print(f"\nBottom 5 recommended beers:\n {bottom5[["beer_name", "similarity"]]}")

"""---
  
Based on the attributes specified by the user **["black", "bourbon", "thick"]**, the top 3 recommended beers are:  
* **Very Hazy** with a cosine similarity of <u>0.839148</u>  
* **Doubleganger** with a cosine similarity of <u>0.828064</u>  
* **Double Dry Hopped Double Citra Daydream** with a cosine similarity of <u>0.820779</u>  
  
---

### **AHA** Moment Discovered!!  

The beer <u>Rocky Road - Bourbon Barrel-Aged</u>(-0.753352) is present in the bottom 5 recommended beers even though its name contains *Bourbon*. **Why?**  

Let's have a closer look at all the reviews of this beer specifically:
"""

rocky_reviews_full_taskc = df[df["beer_name"] == "Rocky Road - Bourbon Barrel-Aged"].copy()
rocky_reviews_full_taskc["attr_sentiment_scores"] = rocky_reviews_full_taskc["review_text"].fillna("").apply(get_attr_sentiment_scores_taskc)
rocky_export_taskc = rocky_reviews_full_taskc[["review_text", "attr_sentiment_scores"]]
rocky_export_taskc.head(20)

"""Here's what’s happening:

1. **Attributes not really triggered**

   * Most reviews have all zeros:

     ```json
     {'black': 0.0, 'bourbon': 0.0, 'thick': 0.0}
     ```
   * Even though reviews literally say *“midnight-black body”* or *“bourbon barrel”*, the regex+context extractor only assigns a score if:

     * The exact token matches the attribute (`black`, `bourbon`, `thick`).
     * And when it does, the **sentiment around it** is often close to 0.

2. **Negative sentiment detected**

   * Example at row `13724`:

     ```json
     {'black': -0.296, 'bourbon': 0.0, 'thick': -0.128}
     ```
   * VADER interpreted the context as slightly **negative** → on multiplying the embedding by this weight, the vector is pushed in the opposite direction of the query.

3. **End effect**

   * Since most reviews = zeros, and one or two = negative weights, the **aggregate beer vector drifts away from the query vector**, hence landing in the **bottom 5**.

---

So the real reason `Rocky Road - Bourbon Barrel-Aged` fell into the bottom is:

* Few/weak mentions of attributes in reviews,
* One negative sentiment mention dragging its vector away,
* No contribution from the beer name.

---

> *Note: Custom word embeddings/spaCy embedding, can overcome this issue by incorporating a vector for beer_name into the weighted review vectors, boosting its relevance even if the reviews don't emphasize it*

7. Top and Bottom 3 beer attribute-level aggregate scores
"""

# Build attribute-level aggregate DataFrame
beer_attr_scores_taskc = {beer: {attr: [] for attr in attributes} for beer in beer_profiles_taskc.keys()}

for _, row in df_taskc.iterrows():
    beer = row["beer_name"]
    attr_scores = row["attr_sentiment_scores"]

    if beer not in beer_attr_scores_taskc:
        continue
    for attr in attributes:
        beer_attr_scores_taskc[beer][attr].append(attr_scores[attr])

# Average per beer per attribute
beer_attr_matrix_taskc = []
beer_names_attr_taskc = []

for beer, attr_dict in beer_attr_scores_taskc.items():
    beer_names_attr_taskc.append(beer)
    beer_vector = []
    for attr in attributes:
        if len(attr_dict[attr]) > 0:
            beer_vector.append(np.mean(attr_dict[attr]))
        else:
            beer_vector.append(0.0)
    beer_attr_matrix_taskc.append(beer_vector)

beer_attr_df_taskc = pd.DataFrame(beer_attr_matrix_taskc, columns=attributes, index=beer_names_attr_taskc)

# Tables
top3_beers = ['Very Hazy', 'Doubleganger', 'Double Dry Hopped Double Citra Daydream']

bottom3_beers = ['Rodenbach Caractère Rouge', 'Rocky Road - Bourbon Barrel-Aged', 'Julius']

print("\nTable 1 - Top 3 beers (attribute-level aggregate scores):")
print(beer_attr_df_taskc.loc[top3_beers])

print("\nTable 2 - Bottom 3 beers (attribute-level aggregate scores):")
print(beer_attr_df_taskc.loc[bottom3_beers])

"""8. Top 20 beer recommmendations based on ["black", "bourbon", "thick"]"""

user_query_taskc = ["black", "bourbon", "thick"]
results = recommend_beers_taskc(user_query_taskc, top_k=20)
print('\nTop 20 recommended beers:')
print(results[['beer_name', 'similarity']])

"""---
  
#### Interpretation and Insights from Task C: Using Word Vectors (spaCy)

In Task B, we used a **bag-of-words cosine similarity** approach. This method depends on exact word overlap between user attributes and beer reviews. While effective, it cannot capture **semantic similarity** (e.g., *"dark"* vs. *"bourbon"*) or the **sentiment behind a review**.

In Task C, we modified the approach by utilizing **spaCy's pre-trained word vectors** (`en_core_web_md`) with **attribute-level sentiment scores** from **VADER**:

1. Vector Representation of Reviews
- Each review was tokenized; stopwords and punctuation were removed; tokens without embeddings were ignored.  
- A **review embedding** was computed as the average of token vectors.  
- For user-specified attributes (*black*, *bourbon*, *thick*), **VADER sentiment scores** were extracted for each occurrence within a review.  
- The **sum of sentiment scores across the attributes** was used to **weight the review embedding**, producing a weighted vector:  
    - `weighted_vector = review_embedding × sum(attribute_sentiments)`

2. Aggregation at Beer Level
- Beers have multiple reviews; **weighted review vectors** were averaged across reviews mentioning at least one attribute.  
- This results in a **beer-level embedding** capturing both semantic content and sentiment emphasis.

3. Attribute-Level Aggregation
- **Per-attribute sentiment scores** were averaged across relevant reviews per beer.  
- This produces a **beer-by-attribute table**, showing how each beer scores on *black*, *bourbon*, and *thick*.

4. Recommender
- User queries (e.g., `["black", "bourbon", "thick"]`) are embedded and compared with **beer-level embeddings** using cosine similarity.  
- Beers are ranked by similarity to generate **Top-N recommendations**.

5. Results
- **Top-3 beers** based on these attributes:  
    * **Very Hazy** --- similarity: 0.839148  
    * **Doubleganger** --- similarity: 0.828064  
    * **Double Dry Hopped Double Citra Daydream** --- similarity: 0.820779  

- **Bottom-3 beers**:  
    * **Rodenbach Caractère Rouge** --- similarity: -0.753720
    * **Rocky Road - Bourbon Barrel-Aged** --- similarity: -0.753352
    * **Julius** --- similarity: -0.718537

- Two separate tables display **average attribute-level sentiment scores** for these beers, providing interpretable insights alongside embedding-based similarity.

6. Comparison with Task B
- **Bag-of-Words (Task B)**: accurate when attributes appear exactly in reviews, but misses semantic similarity and sentiment nuances.  
- **Word Vectors + Attribute Sentiment (Task C)**: captures both **semantic similarity** (e.g., *dark ≈ bourbon*) and **emotional tone**, producing more **nuanced, human-like recommendations**.

---

*Analysis: <u>Which method gives better recommendations in this context?</u>*
- **Semantic awareness**: reviews using different words to describe similar flavors are correctly matched to user preferences.  
- **Sentiment weighting**: positive or negative mentions of attributes influence the beer embeddings, improving recommendation quality.  
- **Top-3 results** reflect both **meaning** and **emotional tone**, providing a more faithful reflection of user intent.  
- **Task B limitations**: misses beers described semantically rather than literally, potentially under-recommending relevant beers.

---

**Conclusion:**  
- **Task B (Bag-of-Words)** is simpler but limited to exact matches.  
- **Task C (Word Vectors)** is more robust, semantically aware, and sentiment-sensitive, leading to **recommendations that better align with user intent**.

---

## TASK D: Crafting Our Own Beer Language - Custom Word Embeddings
"""

# Preprocessing function
def preprocess(text):
    tokens = word_tokenize(text.lower())          # lowercase + tokenize
    tokens = [t for t in tokens if t.isalpha()]   # keep only alphabetic words
    tokens = [t for t in tokens if t not in stop_words]  # remove stopwords
    return tokens   # return list of tokens (not set, so you keep duplicates)

# Apply preprocessing to your dataset
df["tokens"] = df["review_text"].apply(preprocess)

"""We now want to recommend beers based on the attributes- Black, Bourbon and Thick. Instead of recommending by raw word overlap, we build a representation of each beer from its reviews. We then combine semantic information (via Custom Word2Vec embeddings) with sentiment (so positive mentions count more than negative), And finally, we compare beers and attributes using cosine similarity."""

# Setup
nltk.download("vader_lexicon")
sia = SentimentIntensityAnalyzer()

# Attributes of interest
attributes = ["black", "thick", "bourbon"]

"""Now, we are training custom embeddings. The input is df['tokens'].tolist() which is each review preprocessed into a list of tokens. The Word2Vec model learns vector representation (vector size = 100) of words based on how they co-occur in the reviews. They key idea is that words that appear in similar contexts (eg 'citrus','orange','grapefruit') will have similar vectors. So this let's us capture domain-specific semantics from the beer review dataset (not generic language)

"""

# Train custom embeddings

# Assuming df["tokens"] exists from preprocessing
sentences = df["tokens"].tolist()

w2v_model = Word2Vec(
    sentences,
    vector_size=100,
    window=5,
    min_count=2,
    workers=4,
    sg=1  # skip-gram
)

"""Next, for each review we scan tokens- looking for attributes which are 'Black','Bourbon','Thick'. For each mention, extracting its local context (a 7-word window) and compute VADER sentiment. The compund score ranges from -1 to +1. We sum these sentiments values across all mentions in the review (sentiment_sum). We are doing sum and not average because multiple positive mentions strengthen the signal. Then, for each attribute mention, fetch its Word2Vec embeddings and take the mean of embeddings (so a review has one vector summarizing the attributed mentioned). Next, we multiply the averaged embedding by the summed sentiment score. Positive reviews push the vector outward (strong signal) and negative reviews pull it back (weak signal). The final result will be one sentiment-weighted vector per review that encodes both semantic meaning and customer opinion."""

# Review-level representation

def get_review_vector(tokens, attributes, model, sia):
    attr_vecs = []
    sentiment_sum = 0.0

    for i, token in enumerate(tokens):
        if token in attributes and token in model.wv:
            # local context for sentiment
            context = " ".join(tokens[max(0, i-3): i+4])
            sentiment = sia.polarity_scores(context)["compound"]

            sentiment_sum += sentiment
            attr_vecs.append(model.wv[token])

    if len(attr_vecs) == 0:
        return None  # no attributes mentioned in this review

    #average embeddings of mentioned attributes
    avg_attr_vec = np.mean(attr_vecs, axis=0)

    #weight by summed sentiment score
    return avg_attr_vec * sentiment_sum

# Apply to each review
df["review_vector"] = df["tokens"].apply(
    lambda t: get_review_vector(t, attributes, w2v_model, sia)
)

"""Each beer has multiple reviews. For each beer, we average all review vectors (ignoring reviews with no attributes mentioned). This gives one beer profile vector- which captures all mentions of the attributes across reviewers and weighs them by sentiment strength. So the beer vector = Summation (Review Embedding X Sentiment Sum)/ Number of relevant reviews


"""

# Beer-level aggregation

beer_profiles_embed = {}

for beer, group in df.groupby("beer_name"):
    valid_vecs = [v for v in group["review_vector"] if v is not None]
    if len(valid_vecs) > 0:
        beer_profiles_embed[beer] = np.mean(valid_vecs, axis=0)

#Create beer matrix for similarity
beer_names_embed = list(beer_profiles_embed.keys())
beer_matrix_embed = np.vstack(list(beer_profiles_embed.values()))

"""For each of the attributes- Black, Bourbon and Thick, we then check if in vocabulary then we use its embedding, is not then use zeros. We then average the query vector, and no sentiment weighting here becuase the user query is a neutral preference.

Next, we check cosine similarity which measures the angle between query vector and beer profile vectors. The inutuition here is is a beer's reviews are full of positive mentions, its profile vector will be aligned with the query vector. Thus higher similarity = better recommendation.
"""

# Recommender function

def recommend_beers_embed(query_attrs, top_k=3):
    query_vecs = []
    sentiment_dummy = 1.0  # for query we don't have review sentiment

    for attr in attributes:
        if attr in query_attrs and attr in w2v_model.wv:
            query_vecs.append(w2v_model.wv[attr])
        else:
            query_vecs.append(np.zeros(w2v_model.vector_size))

    query_vector = np.mean(query_vecs, axis=0) * sentiment_dummy
    query_vector = query_vector.reshape(1, -1)

    sims = cosine_similarity(query_vector, beer_matrix_embed)[0]
    results = pd.DataFrame({"beer_name": beer_names_embed, "similarity": sims})
    return results.sort_values(by="similarity", ascending=False).head(top_k)

"""We run the recommender and output top 3 beers are recommendations.

"""

# Run recommender
user_query = ["black", "thick", "bourbon"]
results_embed = recommend_beers_embed(user_query, top_k=3)

print("\nTop 3 recommended beers:")
print(results_embed)

"""These beers are highly associated with black colour, bourbon barrel aging and thick feel in their reviews. The recommendations reflect beers that are stout like which matches real-world beer characteristics

**Interpretation on Task D: Custom Word Embeddings**

In Task D, we moved away from SpaCy’s pretrained embeddings and created **custom Word2Vec embeddings** trained directly on our beer review corpus. The idea was to capture how beer drinkers actually use and associate words in this specific domain, rather than relying on general-purpose language models.


**Why this is better than Task C**

* **Domain-specific context:** SpaCy embeddings understand “bourbon” as a spirit and “black” as a color, but they don’t capture their beer-specific associations (e.g., *bourbon barrel aging* with *vanilla* and *oak*, or *black* with *stout*). Training on beer reviews embeds these words in the context of how drinkers actually describe beers.

* **Sharper recommendations:** While Task C’s recommendations (e.g., *Fundamental Forces, Blessed*) reflected general semantic meaning, Task D surfaced beers (*Reaction State, Adjunct Trail, Red Eye November*) that reviewers consistently describe with the exact chosen attributes.

**Key takeaway:**
Custom embeddings provided recommendations that were more **aligned with beer style and review language**, making them better suited than SpaCy’s general-purpose vectors for this recommender task.

## Task E: Ratings Alone - Does Popularity Equal Suitability?

Chosing the 3 highest rated products from the entire dataset

Step 1. We first calculate the average rating for each beer:
"""

# Calculate average rating for each beer
top_rated = df.groupby('beer_name')['reviewer_overall'].mean().sort_values(ascending=False)
top3_rated = top_rated.head(3)
print("Top 3 highest rated beers (ignoring similarity and sentiment):")
print(top3_rated)

"""These are the top 3 beers most liked by reviewers overall, regardless of attributes or sentiment.

Step 2. Ranking the Same Beers Using Custom Embeddings(used in pard D), Sentiment, and Similarity
We use a recommender that ranks beers by how closely their reviews match the attributes ["black", "bourbon", "thick"], and also considers sentiment and cosine similarity.
"""

def search_beers_in_ranked_list(query_attrs, target_beers, top_k=None):
    # Run recommender with full list (or top_k cutoff if you want)
    results = recommend_beers_embed(query_attrs, top_k=len(beer_names_embed))
    results = results.reset_index(drop=True)
    results.index += 1  # make rank start at 1

    found = []
    for beer in target_beers:
        match = results[results["beer_name"].str.lower() == beer.lower()]
        if not match.empty:
            rank = match.index[0]
            similarity = match["similarity"].values[0]
            found.append((beer, rank, similarity))
        else:
            found.append((beer, None, None))
    return found

# Example usage
user_query = ["black", "bourbon", "thick"]
target_beers = ["10 Year Barleywine", "O.W.K.", "M.J.K."]

matches = search_beers_in_ranked_list(user_query, target_beers)

for beer, rank, sim in matches:
    if rank:
        print(f"Beer: {beer}\nRank: {rank}\nCosine similarity: {sim:.4f}\n")
    else:
        print(f"Beer: {beer} not found in ranked list.\n")

"""**Would these products meet the requirements of the user looking for recommendations?**

If we ignore similarity and sentiment scores and simply pick the three highest-rated beers (*10 Year Barleywine, O.W\.K., M.J.K.*), the results do not align well with the user’s preference of *black, bourbon, thick*.

* **Logic**: High average ratings reflect overall product quality but are not attribute-specific. They capture popularity but ignore whether the beers actually match the desired flavor profile.

* **Output**: When checked against the embedding-based recommender, *O.W\.K.* ranked reasonably high (16th, similarity 0.9744), but *10 Year Barleywine* and *M.J.K.* ranked far lower (101st and 121st, respectively).
* **Analysis**: This demonstrates that relying only on ratings fails to satisfy user-defined preferences. The large rank differences highlight how the embedding + sentiment approach better captures attribute relevance from reviews, whereas pure ratings overemphasize popularity.

**Conclusion**

If we use only ratings:

- We get the beers most liked by all reviewers, but they may not match your specific preferences.

If you use attributes, sentiment, and similarity:
- You get beers that are more relevant to your taste, but the most popular beers may not rank highest.

## TASK F: Meet the Competition - Finding Your Closest Beer Rival

Pick any 10 beers + anchor
"""

sampled_beers = [
    "Ten FIDY - Bourbon Barrel-Aged",
    "Trappistes Rochefort 10",
    "Abraxas",
    "Fundamental Observation",
    "Trappist Westvleteren 12 (XII)",
    "Pliny The Younger",
    "Pirate Bomb!",
    "Double Stack",
    "Bourbon Paradise",
    "Doppelganger",
]
reference_beer = "Doppelganger"

df10 = df[df["beer_name"].isin(sampled_beers)].copy()
print(f"Reference beer: {reference_beer}")
print(f"# Reviews in the 10-beer subset: {len(df10)}")

"""TF-IDF on the 10 beers → show top 50 words (for manual attribute picking)"""

beer_docs = (
    df10.groupby("beer_name")["tokens"]
        .apply(lambda lists: " ".join([" ".join(toks) for toks in lists]))
)

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(beer_docs.values)   # shape: (#beers x |V|)
vocab = vectorizer.get_feature_names_out()

# overall importance = sum TF-IDF across beers (simple, effective)
import numpy as np
overall = np.asarray(X.sum(axis=0)).ravel()
top_idx = overall.argsort()[::-1][:50]
top_terms = pd.DataFrame({
    "term": vocab[top_idx],
    "score": overall[top_idx]
}).reset_index(drop=True)

print("Top 50 TF-IDF terms across the 10 beers:")
top_terms.head(50)

"""Manually pick attribute terms"""

selected_attributes  = [
    # Flavor
    "chocolate", "vanilla", "bourbon", "coffee", "sweet", "maple",
    "citrus", "rum", "coconut", "chili", "alcohol", "caramel",
    "cinnamon", "fruit", "roasted",

    # Appearance
    "dark", "brown", "black", "light",

    # Aroma / Nose
    "aroma", "nose",

    # Texture / Mouthfeel
    "smooth", "malt", "barrel", "rich", "feel", "mouthfeel", "lacing"
]

#show which of your top TF-IDF terms are in the attribute list
attr_in_top = [t for t in selected_attributes if t in set(top_terms["term"].tolist())]
print("Attributes that appear in top-50 TF-IDF:", attr_in_top)

"""Train Word2Vec on the 10 beers"""

sentences = df10["tokens"].tolist()

w2v = Word2Vec(
    sentences=sentences,
    vector_size=100,
    window=5,
    min_count=2,
    workers=4,
    sg=1  # skip-gram
)

"""Build one vector per beer (average embeddings of selected attributes)"""

beer_vectors = {}

for beer, group in df10.groupby("beer_name"):
    # flatten tokens for this beer
    flat = [tok for toks in group["tokens"] for tok in toks]
    counts = Counter(t for t in flat if t in selected_attributes and t in w2v.wv.key_to_index)
    if not counts:
        # fallback: zero vector if no selected attributes found
        beer_vectors[beer] = np.zeros(w2v.vector_size, dtype=float)
        continue
    vec_sum = np.zeros(w2v.vector_size, dtype=float)
    weight_sum = 0.0
    for term, freq in counts.items():
        vec_sum += w2v.wv[term] * float(freq)
        weight_sum += float(freq)
    beer_vectors[beer] = vec_sum / weight_sum

# Build matrix in the same beer order:
beer_names_embed = list(beer_vectors.keys())
beer_matrix_embed = np.vstack([beer_vectors[b] for b in beer_names_embed])

print("beer_matrix_embed shape:", beer_matrix_embed.shape)

"""Cosine similarity: compare all 9 beers to Doppelganger"""

# ensure the anchor is in our computed list
assert reference_beer in beer_names_embed, f"{reference_beer} missing in vectors"

ref_idx = beer_names_embed.index(reference_beer)
ref_vec = beer_matrix_embed[ref_idx].reshape(1, -1)

# other beers among the chosen 10
others = [b for b in sampled_beers if b != reference_beer and b in beer_names_embed]
other_idx = [beer_names_embed.index(b) for b in others]
other_vecs = beer_matrix_embed[other_idx]

sims = cosine_similarity(ref_vec, other_vecs)[0]
results = pd.DataFrame({"beer_name": others, "similarity": sims}).sort_values("similarity", ascending=False)
results.reset_index(drop=True, inplace=True)
results

"""**Interpretation of Task F: Doppelganger's closest beers among the selected 10**

We selected 10 beers and used *Doppelganger* as our reference. We applied TF-IDF to extract the most frequent terms from reviews and manually filtered them down to meaningful beer attributes (flavor, aroma, appearance, mouthfeel, barrel-aging, etc.).

Next, we trained Word2Vec embeddings restricted to these attribute terms and created a beer-level profile vector by averaging the attribute embeddings across all reviews for each beer.

Finally, we computed cosine similarity between *Doppelganger’s* attribute vector and those of the other 9 beers.

**Results**
The most similar beer to *Doppelganger* is:

* **Pliny The Younger** (cosine similarity = 0.998)

Other close contenders include:

* *Trappistes Rochefort 10* (0.992)
* *Trappist Westvleteren 12 (XII)* (0.989)
* *Double Stack* (0.988)
* *Ten FIDY – Bourbon Barrel-Aged* (0.988)

**Conclusion**  
This result makes intuitive sense. *Pliny The Younger* is a highly regarded IPA, often described with citrus, resin, and hop-forward notes, which aligns closely with the descriptive style of *Doppelganger*. The other highly similar beers (e.g., Belgian Trappist ales like Rochefort 10 and Westvleteren 12, or strong stouts like Ten FIDY and Abraxas) reflect overlapping vocabulary around richness, bold flavors, and complexity. The fact that these styles surface highlights how shared descriptors can bridge beer categories.

Thus, our approach successfully demonstrates how text-based embeddings can capture stylistic similarity across beers by learning from the way drinkers describe them.

---


One might argue that word embeddings can blur distinctions when semantically different words appear in similar contexts. While this is a valid caution, in the domain of beer reviews this “blurring” is often a **feature rather than a flaw**.

* **Attribute clusters matter:** Reviewers don’t describe beers with single isolated words—they describe *clusters of related attributes* (e.g., *bourbon–vanilla–oak* for barrel-aged stouts, *citrus–pine–grapefruit* for IPAs). Embeddings naturally pull such descriptors closer together, which mirrors how styles are perceived in practice.

* **Focused vocabulary:** We restricted our embeddings to a curated set of beer attributes rather than the entire vocabulary. This reduces the risk of collapsing unrelated words and ensures we compare beers only on meaningful descriptive dimensions.

* **Complementary to BoW:** Bag-of-words and TF-IDF capture distinctions through frequency, but embeddings add nuance by recognizing similarity across related terms (e.g., *grapefruit* vs. *citrusy*). In combination, they give both clarity and depth.

In short, while embeddings may not outperform frequency-based models in every domain, for beer style comparisons they provide a **philosophically aligned and intuitively satisfying lens**, capturing the way drinkers naturally group and compare beers.

# THE END
"""